### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by testfooyy** [noppefoxwolf/FlowBarButtonItem#5]
![2018-06-30 12 40 46](https://user-images.githubusercontent.com/28691623/42121116-44c6b4bc-7c63-11e8-88ca-7ee72c66711b.png)

**Comment by noppefoxwolf** [comment]
ButtonItem Must be initialize from code.(not storyboard

**Comment by noppefoxwolf** [comment]
If you initialize from storyboard, plz PR your code or wait my action.

**Comment by noppefoxwolf** [comment]
Close this issue.If you have more issue, please ope new issue page.
